swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths: 
  /accounts:
    get:
      security:
        - Bearer : []
      tags:
      - Accounts
      summary: "Gets all user accounts"
      description: "Returns a list of user accounts"
      produces:
      - "application/json"
      parameters: 
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      responses:
        "200":
          description: "Accounts retrieved successfully"
          schema:
            $ref: '#/definitions/Accounts'
        '401':
          description: Authorization error
        "500":
          description: Internal Server Error
  /accounts/{accountId}:        
    get:
      security:
        - Bearer : []
      tags:
      - Accounts
      summary: "Gets single user account"
      description: "Returns a user account"
      produces:
      - "application/json"
      parameters: 
      - in: path
        name: accountId
        description: Account id
        required: true
        type: string
      responses:
        "200":
          description: "Account retrieved successfully"
          schema:
            $ref: '#/definitions/Account'
        '401':
          description: Authorization error
        "404": 
          description: "Account does not exist"
        "500":
          description: "Internal Server Error"
  /accounts/{accountId}/transactions:
    get:
      security:
        - Bearer : []
      tags:
      - Transactions
      summary: "Gets all user transactions"
      description: "Returns a list of user transactions"
      produces:
      - "application/json"
      parameters: 
      - in: path
        name: accountId
        description: Account id
        required: true
        type: string
      responses:
        "200":
          description: "Transactions retrieved successfully"
          schema:
            $ref: '#/definitions/Transactions'
        '401':
          description: Authorization error
        "500":
          description: "Internal Server Error"
  /accounts/{accountId}/transactions/{transactionId}:
    get:
      security:
        - Bearer : []
      tags:
      - Transactions
      summary: "Gets single user transaction"
      description: "Returns a user transaction"
      produces:
      - "application/json"
      parameters: 
      - in: path
        name: accountId
        description: Account id
        required: true
        type: string
      - in: path
        name: transactionId
        description: Transaction id
        required: true
        type: string
      responses:
        "200":
          description: "Transaction retrieved successfully"
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: Authorization error
        "404":
          description: "Transaction does not exist"
        "500":
          description: "Internal Server Error"      
    patch:
      security:
        - Bearer : []
      tags:
      - Transactions
      summary: "Updates category/note transaction"
      description: "Updates category/note transaction"
      parameters: 
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update category transaction name
          required: true
          schema:
            $ref: '#/definitions/Edit'
        - in: path
          name: accountId
          description: Account id
          required: true
          type: string
        - in: path
          name: transactionId
          description: Transaction id
          required: true
          type: string
      produces:
        - application/json
      responses: 
        "200":
          description: "Category transaction updated successfully"
          schema:
            $ref: "#/definitions/Edit"
        "400":
          description: Invalid fields
        '401':
          description: Authorization error          
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Account:
    type: object
    properties:
      accountId: 
        type: integer
        format: int64
      name:
        type: string
      amount:
        type: integer
        format: int64
  Accounts: 
    type: array
    items: 
      $ref: "#/definitions/Account"
  Edit:
    type: object
    properties:
      category:
        type: string
      note:
        type: string
  Transaction:
    type: object
    properties:
      date:
        type: string
      description:
        type: string
      amount: 
        type: integer
        format: int64
      balance:
        type: integer
        format: int64
      category:
        type: string
      note: 
        type: string
  Transactions: 
    type: array
    items: 
      $ref: "#/definitions/Transaction"